object = {
    "TG": ["id","Patent ID","Split Tagging","Status","Family","digit","Patent Ref","App Title","Country","Filed Date","First Filing","Application Number","Grant Date","Patent No.","Responsible Manager","Applicants","Clients","Current Owners","Annuity Agent","Primary Law Firm","IP Sites"],
    "Invoice": ["id","Action","Status","Case","Firma","Numer faktury","Data wystawienia","Opis","Czy wprowadzona do AQ","Czy skopiowana na R","Czy wysłana do Lipska","Numer dokumentu w WF","Czy zweryfikowana w WF","Czy zaakceptowana w WF","Czy płatność zrealizowana","Comment"],
    "EL": ["id","ID","Firma","Case","Opis","Numer EL","Czy podpisany przez kancelarię","Czy komplet podpisów z ABB","Czy wysłany do kancelarii","Czy wysłany do B.R.","Czy mam papierową wersję podpisanego EL"],
    "PoA": ["id","Case","Kancelaria","Reprezentant ABB","Urząd Patentowy","Czy EPO Authorisation zredagowane i wysłane do podpisu","Czy uzyskane pełnomocnictwo (EPO Authorisation)","Czy mam oryginał lub kopię","Czy potwierdzone przez UP"],
    "FF steps": ["id","Status","PG-SO","Split tagging","Invention ID","Case Reference","Case history","IPSO","Czy założony folder na R","Czy założona teczka","Law Firm w AQ","Law Firm Sign","Authorisation","Kto pisze - kancelaria","Kto pisze - osoba","Osoba kontaktowa w ABB","Czy wysłane materiały do kancelarii","(D) Numer EL","(D) Data zlecenia","Faktyczna data odbioru","(D) Numer dokumentu w WF","Kto składa - kancelaria","Kto składa - osoba","(F) Numer EL","(F) Data zlecenia","Data złożenia","Kraj","Numer zgłoszenia","Numer publikacji","Tytuł zgłoszenia","Czy dokumenty zgłoszeniowe skopiowane na R","Czy dokumenty zgłoszeniowe włożone do teczki","Czy zrobiony wpis do zeszytu","Czy w AQ wprowadzone dane o zgłoszeniu","Czy w AQ załączone pliki zgłoszeniowe","Czy złożony wniosek o wynagrodzenie dla twórców","Czy wysłany e-mail do twórców","Czy jest potwierdzenie wypłaty wynagrodzenia","Czy wysłane powiadomienie do twórców zagranicznych","(S) Numer dokumentu w WF","(F) Numer dokumentu w WF","Czy pszyszedł raport","Czy raport skopiowany na R","Czy twórcy powiadomieni","Czy raport skopiowany do AQ","czy opinia wstawiona do AQ","Czy jest decyzja w AQ","Kancelaria","(E) Numer EL","(E,S) Numer dokumentu w WF","(E,F) Numer dokumentu w WF","Inna faktura","Opis faktury","Comments"],
    "Case history": ["id","Quick select","Case reference","History"],
    "History (other)": ["id","ID","History"],
    "To Do": ["id","Status","Data wpisu","AKCJA","Flag"]
}